name: Test Action

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build action
        run: |
          npm ci
          npm run build

      - name: Run local action
        uses: ./
        with:
          model: free